development:
  adapter: postgresql
  database: perilous_journey_development
  pool: 5
  timeout: 5000

test: 
  adapter: postgresql
  database: perilous_journey_development
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: perilous_journey_development
  pool: 5
  timeout: 5000

